# Generated by Django 5.2.1 on 2025-05-16 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_country_alter_address_options_book_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='published_countries',
        ),
    ]
